vsapp/urls.py
from django.urls import path
from vsapp import views
from .views import MovieListView, MovieDetailView,  review_list, review_detail
from django.conf import settings
from django.conf.urls.static import static

app_name = 'vsapp'

urlpatterns = [
    path('', MovieListView.as_view(), name='movies_list'),
    path('movie/<slug>/', MovieDetailView.as_view(), name='movies_detail'),
    # path('movie/<slug>/(<movie_id>[0-9]+,)/add_review/', views.add_review, name='add_review'),
    # path("movie/<slug:slug>/review/", view=ReviewCreate.as_view(), name="review", ),
    path('review_list/', views.review_list, name='review_list'),
    path('review/<review_id>/', views.review_detail, name='review_detail'),
]

if settings.DEBUG is True:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

vsproject/urls.py
from django.contrib import admin
from django.urls import path,include
import vsapp.urls
from vsapp.views import LandingPageView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,LogoutView
admin.site.site_header = 'Vsapp Administration'
admin.site.site_title = 'Movies Administration'
admin.site.index_title = 'Movies Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vsapp/',include('vsapp.urls',namespace='vsapp')),
    path('',LandingPageView.as_view(),name='landing-page'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vsapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone


# Create your models here.
class User(AbstractUser):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField()


class Movies(models.Model):
    mainimage = models.ImageField(upload_to='vsapp/', blank=True)
    name = models.CharField(max_length=50)
    slug = models.SlugField()
    genre = models.CharField(max_length=20, default='genre')
    release_period = models.CharField(max_length=20, default='release period')
    preview_text = models.TextField(max_length=150, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=500, verbose_name='Detail Text')
    directors = models.CharField(max_length=200, null=True)
    writers = models.CharField(max_length=200, null=True)
    stars = models.CharField(max_length=200, null=True)

    class Meta:
        verbose_name = 'Movie'
        verbose_name_plural = 'Movies'

    def __str__(self):
        return self.name


class Review(models.Model):
    movie = models.ForeignKey(Movies, related_name='reviews', on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    user_name = models.CharField(max_length=100, default="Unknown user")
    comment = models.TextField(max_length=1000)
    rating = models.IntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])
    slug = models.SlugField()
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("vsapp:review_detail", kwargs={"review_id": self.id})

vsapp/forms.py
from django import forms
from django.forms import ModelForm,Textarea
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model
from .models import Review

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    class  Meta:
       model = User
       fields = ('username',)
       field_classes = { 'username':UsernameField }



class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['user_name', 'rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15})
        }

vsapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Movies, Review
from .filters import MoviesFilter
from .forms import CustomUserCreationForm, ReviewForm
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime


# Create your views here.
class LandingPageView(TemplateView):
    template_name = 'vsapp/landing.html'


class MovieListView(ListView):
    model = Movies
    template_name = 'vsapp/movies_list.html'
    context_object_name = 'movies'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = MoviesFilter(self.request.GET, queryset=self.get_queryset())
        return context


class MovieDetailView(DetailView,  CreateView):
    model = Movies
    context_object_name = 'movies'
    form_class = ReviewForm
    template_name = 'vsapp/movies_detail.html'
    queryset = Movies.objects.all()


# class ReviewCreate(CreateView):
#     model = Review
#     form_class = ReviewForm
#     context_object_name = 'reviews'
#     template_name = 'reviews/review.html'
#
#     def get_success_url(self):
#         return reverse('vsapp:movies_detail', kwargs={'slug': self.object.movie.slug})
#

def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list': latest_review_list}
    return render(request, 'reviews/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})

vsapp/templates/reviews/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav  class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'vsapp:review_list' %}">Movies</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'vsapp:movies_list' %}">Movie list</a></li>
                <li><a href="{% url 'vsapp:review_list' %}">Home</a></li>
            </ul>
        </div>
    </nav>
    
    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}

    {% endblock %}
</div>

{% endblock %}

vsapp/templates/reviews/review.html
{% extends "vsapp/movies_detail.html" with object.slug=request.GET.slug %}
{% block title %} New Review for {{ user.username }}{% endblock %}

{% block content %}


{% endblock content %}

vsapp/templates/reviews/review_detail.html
{% extends 'reviews/base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>{{ movie.name }}</h2>
<h5>{{ movie.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>
{% endblock %}

{% block content %}
<h3>Recent reviews</h3>

{% if movie.reviews.all %}
<div>
    {% for review in movie.reviews.all %}
    <div>
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this movie yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{#<form action="{% url 'vsapp:add_review' movie.id %}" method="post" class="form">#}
{#    {% csrf_token %}#}
{#    {% bootstrap_form form layout='inline' %}#}
{#    {% buttons %}#}
{#    <button type="submit" class="btn btn-primary">#}
{#      {% bootstrap_icon "star" %} Add#}
{#    </button>#}
{#    {% endbuttons %}#}
{#</form>#}
{% endblock %}

vsapp/templates/reviews/review_list.html
{% extends 'reviews/base.html' %}

{% block title %}
<h2>Latest reviews</h2>
{% endblock %}

{% if latest_review_list %}
<div>
    {% for review in latest_review_list %}
    <div>
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.movie.name }}
        </a></h4>
        <h6>rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}

vsapp/templates/vsapp/landing.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Video membership site</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
   
 

    <!-- Bootstrap core CSS -->
   <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="landing.css" rel="stylesheet" type="text/css">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Landing-Page</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="{% url 'landing-page' %}">Home</a>
        <a class="nav-link" href="{% url 'vsapp:movies_list' %}">Movies</a>
      </nav>
    </div>
  </header>

  <main class="px-3">
    <h1>Hello there</h1>
    <div class="container" style="text-align: center;">
      <p style="text-align: center;" class="lead"> Welcome to our blog,please do not forget the Preview and review the movies and leave us with positive feedback </p>
    </div>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white text-black-50">Learn more</a>
    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p><a href="https://getbootstrap.com/" class="text-white"></a>, <a href="#" class="text-white"></a>.</p>
  </footer>
</div>


    
  </body>
</html>

vsapp/templates/vsapp/movies_detail.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Movies Detail</title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/blog/">

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="movies.css" rel="stylesheet">
  </head>
  <body>
    
<div class="container">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="link-secondary" href="#"></a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="{% url 'landing-page' %}">Home</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a  href="#"></a>
          </div>
        </div>
      </header>
</div>
<br>
  
<h2 style="text-align: center;">{{object.name}}</h2>
<br>

<main class="container">
  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">{{object.genre}}</strong>
          <h3 class="mb-0">{{object.name}}</h3>
          <div class="mb-1 text-muted">{{object.release_period}}</div>
          <p class="card-text mb-auto">{{object.preview_text}}</p>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg src="{{ object.mainimage }}" class="bd-placeholder-img" width="200" height="300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{object.mainimage}}</text></svg>
          <!--div class="img-wrap"> 
            <img src="media/{{ movie.mainimage }}" style="width: 200%; height: 250px;">
         </div-->
        </div>
      </div>
    </div>
    <dl>
      <dt>STARRING</dt>
      <dd>{{object.stars}}</dd>
      <dt>WRITER(S)</dt>
      <dd>{{object.writers}}</dd>
      <dt>DIRECTOR</dt>
      <dd>{{object.directors}}</dd>
    </dl>
</main>
<br>
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4">Hello, there!</h1>
    <p class="lead">{{object.detail_text}}</p>
    <hr class="my-4">
    <p>Add your review below if you have seen this movie.</p>
    <p class="lead">

      
    </p>
  </div>
</div>
<div class="col Movie-form">
  <h1>Add New Review {{ object }}</h1>

  <form class="form-group" action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary btn-lg" href="#" role="button" value="Add Review  🙃😶" />
  </form>
</div>
{% for review in reviews  %}
<div class="container-fluid"> 
  <div class="col Movie-form">
    <form class="form-group" action="" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <!--input style="text-align: center;" type="submit" class="btn btn-movie" / -->
      <input type="text" name="{{review.comment}}" >
    </form>
  </div>
</div>
{% endfor %}


{% block content %}
  
{% endblock  %}
</body>
</html>

vsapp/templates/vsapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
          <a class="nav-link" href="#">Features</a>
          <a class="nav-link" href="#">Pricing</a>
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </div>
      </div>
    </div>
  </nav>

vsapp/templates/vsapp/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign up</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body> 
    <h3 style="text-align: center;">Sign-up</h3>

        <div class="container-fluid">
            <form>
              <div class="form-group">
                <label for="username" class="form-label" required><strong>Username</strong></label>
                <input type="text" class="form-control form-style" id="username" aria-describedby="" placeholder="Username">
              </div>
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label"><strong>Email address</strong></label>
                  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="john123@example.com" required> 
                  <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label"><strong>Password</strong></label>
                  <input type="password" class="form-control" id="exampleInputPassword1" placeholder="please input a strong password" required>
                </div>
                <div class="mb-3 form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1">
                  <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <div class="container">
                  <div >
                    <button style="display: block; margin: 0 auto;" class="w-50 btn btn-lg btn-primary" type="submit">Sign up !</button>
                  </div>
                </div>
              </form>
        </div>
        <div class="py-5 border-t border-gray-200  mt-3 container-fluid" style="text-align: center;">
          <a class="hover:text-blue-500 mt-3 " href="{% url 'login' %}" >Already have an account?</a>
      </div>
</body>
</html>